lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # required for token creation
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # required for token verification
    pass_phrase:      'ProjectWuja'        # required for token creation, usage of an environment variable is recommended
    token_ttl:        7200                           # default is 3600 seconds
    user_identity_field: username
    token_extractors:
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization
        cookie:
            enabled: false
            name:    BEARER
        query_parameter:
            enabled: true
            name:    bearer