fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_login:
    path: /login
    defaults: { _controller: FOSUserBundle:Security:login }
    options:
        expose: true

app_login_check:
    path: /login_check
    defaults: { _controller: FOSUserBundle:Security:checkAction }
    options:
        expose: true
