parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,View,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    app.login.listener:
        class: App\EventListener\LoginListener
        public: true
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

    app.form.registration:
        class: App\Form\Type\RegistrationFormType
        arguments:
            $class: App\Model\User
        tags:
            - { name: form.type, alias: app_user_registration }



